interface Style {
  reset: number;
  bold: number;
  dim: number;
  italic: number;
  underline: number;
  inverse: number;
  hidden: number;
  strikethrough: number;
}
interface Foreground {
  black: number;
  red: number;
  green: number;
  yellow: number;
  blue: number;
  magenta: number;
  cyan: number;
  white: number;
  gray: number;
  brightRed: number;
  brightGreen: number;
  brightBlue: number;
  brightMagenta: number;
  brightCyan: number;
  brightWhite: number;
}
interface Background {
  bgBlack: number;
  bgRed: number;
  bgGreen: number;
  bgYellow: number;
  bgBlue: number;
  bgMagenta: number;
  bgCyan: number;
  bgWhite: number;
  bgGray: number;
  bgBrightRed: number;
  bgBrightGreen: number;
  bgBrightYellow: number;
  bgBrightBlue: number;
  bgBrightMagenta: number;
  bgBrightCyan: number;
  bgBrightWhite: number;
}

export var foreground: Foreground;
export var background: Background;
export var style: Style;
export function create(color: number): string;
export function reset(msg: string): string;
export function bold(msg: string): string;
export function dim(msg: string): string;
export function italic(msg: string): string;
export function underline(msg: string): string;
export function inverse(msg: string): string;
export function hidden(msg: string): string;
export function strikethrough(msg: string): string;
export function black(msg: string): string;
export function red(msg: string): string;
export function green(msg: string): string;
export function yellow(msg: string): string;
export function blue(msg: string): string;
export function magenta(msg: string): string;
export function cyan(msg: string): string;
export function white(msg: string): string;
export function gray(msg: string): string;
export function brightRed(msg: string): string;
export function brightGreen(msg: string): string;
export function brightBlue(msg: string): string;
export function brightMagenta(msg: string): string;
export function brightCyan(msg: string): string;
export function brightWhite(msg: string): string;
export function bgBlack(msg: string): string;
export function bgRed(msg: string): string;
export function bgGreen(msg: string): string;
export function bgYellow(msg: string): string;
export function bgBlue(msg: string): string;
export function bgMagenta(msg: string): string;
export function bgCyan(msg: string): string;
export function bgWhite(msg: string): string;
export function bgGray(msg: string): string;
export function bgBrightRed(msg: string): string;
export function bgBrightGreen(msg: string): string;
export function bgBrightYellow(msg: string): string;
export function bgBrightBlue(msg: string): string;
export function bgBrightMagenta(msg: string): string;
export function bgBrightCyan(msg: string): string;
export function bgBrightWhite(msg: string): string;